export type DunkTier = 'Beginner' | 'Intermediate' | 'Advanced' | 'Expert' | 'Legendary' | 'Mythic' | 'Godly'

export const TIER_POINTS: Record<DunkTier, number> = {
  Beginner: 10,
  Intermediate: 20,
  Advanced: 40,
  Expert: 70,
  Legendary: 120,
  Mythic: 200,
  Godly: 350,
}

export const TIER_COLORS: Record<DunkTier, string> = {
  Beginner: '#5a6470',
  Intermediate: '#3df5b0',
  Advanced: '#4a9eff',
  Expert: '#c97b42',
  Legendary: '#f5c842',
  Mythic: '#c084fc',
  Godly: '#f54242',
}

export interface Dunk {
  name: string
  tier: DunkTier
}

export const DUNKS: Dunk[] = [
  { name: 'One Hander', tier: 'Beginner' },
  { name: 'Two Hander', tier: 'Beginner' },
  { name: 'Off Glass', tier: 'Beginner' },
  { name: 'Back Scratcher', tier: 'Intermediate' },
  { name: '360', tier: 'Intermediate' },
  { name: 'Windmill', tier: 'Intermediate' },
  { name: 'Reverse 2 hands', tier: 'Intermediate' },
  { name: 'Reverse 1 hand', tier: 'Intermediate' },
  { name: 'Transfer', tier: 'Intermediate' },
  { name: 'D tap', tier: 'Intermediate' },
  { name: 'Reverse Pump', tier: 'Advanced' },
  { name: 'Eastbay', tier: 'Advanced' },
  { name: 'Behind the back', tier: 'Advanced' },
  { name: 'Slingshot', tier: 'Advanced' },
  { name: '180 two-hand windmill', tier: 'Advanced' },
  { name: 'Windmill off glass', tier: 'Advanced' },
  { name: 'Two-hand windmill', tier: 'Advanced' },
  { name: 'Push off windmill', tier: 'Advanced' },
  { name: 'Hand off windmill', tier: 'Advanced' },
  { name: 'J-Rich', tier: 'Advanced' },
  { name: 'Push off J-Rich', tier: 'Advanced' },
  { name: 'Push off btb', tier: 'Advanced' },
  { name: 'Hand off btb', tier: 'Advanced' },
  { name: 'Push off underboth', tier: 'Advanced' },
  { name: 'Hand off underboth', tier: 'Advanced' },
  { name: 'Double Transfer', tier: 'Advanced' },
  { name: 'D tap reverse', tier: 'Advanced' },
  { name: 'Double d tap', tier: 'Advanced' },
  { name: '360 scoop', tier: 'Advanced' },
  { name: 'Honey-Dip', tier: 'Expert' },
  { name: 'Thrunk', tier: 'Expert' },
  { name: '360 Windmill', tier: 'Expert' },
  { name: 'Off vert windmill', tier: 'Expert' },
  { name: 'Back scratcher windmill', tier: 'Expert' },
  { name: 'Windmill Elbow', tier: 'Expert' },
  { name: '360 Eastbay', tier: 'Expert' },
  { name: 'Eastbay off-glass', tier: 'Expert' },
  { name: 'Push off eastbay', tier: 'Expert' },
  { name: 'Eastbay off wall', tier: 'Expert' },
  { name: 'Eastbay off side of glass', tier: 'Expert' },
  { name: 'Btb off side of glass', tier: 'Expert' },
  { name: 'Eastbay two hand finish', tier: 'Expert' },
  { name: 'Eastbay reverse one hand finish', tier: 'Expert' },
  { name: 'Off glass btb', tier: 'Expert' },
  { name: '360 btb', tier: 'Expert' },
  { name: '360 J-Rich', tier: 'Expert' },
  { name: 'Fake eastbay', tier: 'Expert' },
  { name: 'Fake J-Rich', tier: 'Expert' },
  { name: 'Tetris', tier: 'Expert' },
  { name: 'Happy feet', tier: 'Expert' },
  { name: 'Crystal Ball', tier: 'Expert' },
  { name: 'Volleyball spike', tier: 'Expert' },
  { name: 'Double back scratcher', tier: 'Expert' },
  { name: '180 Crystal ball', tier: 'Expert' },
  { name: 'Eastbay where you bounce it and only use one hand', tier: 'Expert' },
  { name: 'Underboth', tier: 'Legendary' },
  { name: 'Double Honey Dip', tier: 'Legendary' },
  { name: 'Push-off Crown', tier: 'Legendary' },
  { name: 'Reverse direction windmill', tier: 'Legendary' },
  { name: 'Eastbay reverse two-hand finish', tier: 'Legendary' },
  { name: 'Off vert eastbay', tier: 'Legendary' },
  { name: 'Off Vert btb', tier: 'Legendary' },
  { name: 'Btb scorpion', tier: 'Legendary' },
  { name: '360 underboth', tier: 'Legendary' },
  { name: 'Off glass underboth', tier: 'Legendary' },
  { name: 'Underboth two hand finish', tier: 'Legendary' },
  { name: 'Under both reverse finish', tier: 'Legendary' },
  { name: 'Back flip dunk', tier: 'Legendary' },
  { name: 'Christ Air', tier: 'Legendary' },
  { name: 'Splits dunk', tier: 'Legendary' },
  { name: 'Captain Morgan', tier: 'Legendary' },
  { name: 'Cannon ball', tier: 'Legendary' },
  { name: 'Flying Squirrel', tier: 'Legendary' },
  { name: 'Criss-cross apple sauce dunk', tier: 'Legendary' },
  { name: 'Snake', tier: 'Legendary' },
  { name: 'Backscratcher into pump reverse', tier: 'Legendary' },
  { name: 'Double pump reverse', tier: 'Legendary' },
  { name: 'Crystal ball touch back of head reverse', tier: 'Legendary' },
  { name: 'Backscratcher happy feet', tier: 'Legendary' },
  { name: 'Kamikaze', tier: 'Godly' },
  { name: 'Backscratcher Eastbay', tier: 'Mythic' },
  { name: '360 Double Eastbay', tier: 'Godly' },
  { name: '360 eastbay 2 hand finish', tier: 'Mythic' },
  { name: 'Eastbay Btb', tier: 'Godly' },
  { name: 'Eastbay btb pushoff', tier: 'Mythic' },
  { name: 'Hide and seek', tier: 'Godly' },
  { name: 'Lost and Found', tier: 'Mythic' },
  { name: 'Jonathans wall', tier: 'Godly' },
  { name: 'Jusfly round off dunk', tier: 'Mythic' },
  { name: 'Jusfly Round off dunk eastbay', tier: 'Godly' },
  { name: '360 happy feet', tier: 'Mythic' },
  { name: 'Backscratcher double elbow', tier: 'Mythic' },
  { name: 'Upside down dunk', tier: 'Mythic' },
  { name: 'Transfer elbow', tier: 'Mythic' },
  { name: '360 Double elbow', tier: 'Mythic' },
  { name: '360 Windmill Elbow', tier: 'Mythic' },
  { name: 'Butterfly effect', tier: 'Mythic' },
  { name: '180 Snake', tier: 'Mythic' },
  { name: 'Back Flip Eastbay', tier: 'Godly' },
  { name: '360 eastbay off glass', tier: 'Mythic' },
  { name: 'Off vert 360 eastbay', tier: 'Godly' },
  { name: 'Eastbay Elbow', tier: 'Mythic' },
  { name: 'Eastbay Scorpion', tier: 'Mythic' },
  { name: 'Btb Elbow', tier: 'Mythic' },
  { name: 'Underboth scorpion', tier: 'Mythic' },
  { name: '360 Double elbow', tier: 'Mythic' },
  { name: 'Crown', tier: 'Mythic' },
  { name: '540', tier: 'Mythic' },
  { name: 'Eastbay btb pushoff', tier: 'Mythic' },
  { name: 'Double Transfer', tier: 'Advanced' },
  { name: '720', tier: 'Godly' },
]
